- hosts: all
  user: centos
  become: yes 
  become_user: root
  
  roles:
    - etais 

  tasks:
  - name: Testing this out
    debug: msg=Hello user {{ansible_user_id}} on server {{ansible_hostname}}!

- hosts: localhost
  user: centos
  become: yes
  vars:
    hostname: c31348
    domain_name: sa.cs.ut.e

  roles:
   - {role: etais, tags: etais}
   - { role: dns, tags: dns }
