  - name: Add user scoring as Linux user
    user:
      name: scoring
  - name: Create .ssh directory
    file: 
      path: /home/scoring/.ssh
      state: directory
      owner: scoring
      group: scoring
      mode: '0700'
        
  - name: Create the /etc/sudoers.d/scoring file
    lineinfile:
      dest: /etc/sudoers.d/scoring
      line: "scoring ALL=(ALL) NOPASSWD: ALL"
      state: present
      create: yes
