- name: Install Python
  dnf:
    name: python3-pip
    state: latest

- name: Install flask
  pip:
    name: flask
    state: latest

- name: Create a random python file
  template:
    src: python_flask.j2
    dest: "{{home}}/website.py"
    owner: root
    group: root
    mode: '664'

- name: Seboolean | this equates to 'setsebool -P httpd_can_network_connect=1'
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
# Pay attention when you create this file to change the path for the vm name and the domain name
- name: Create the proxy.conf file in etc/httpd/conf.d/proxy.conf
  template:
    src: proxy.conf.j2
    dest: "{{etc}}/httpd/conf.d/proxy.conf"
    owner: root
    group: root
    mode: '664'

- name: Create the zone file for proxy in /etc/named/dns.zone
  template:
    src: dns.zone.j2
    dest: "{{etc}}/named/{{hostname}}.{{domain_name}}"

- name: Create a proxy user
  user:
    name: proxy
      #To use the following part properly we should remove the {{home}}
      #and put the file directly into /usr/local/lib/server.py
- name: Move the python file website.py to /usr/local/lib/server.py
  command: mv {{home}}/website.py {{home}}/usr/local/lib/server.py

- name: Give the ownership to proxy user
  file:
    path: "{{home}}/usr/local/lib/server.py"
    owner: proxy
    group: proxy

- name: Create the file for the proxy service /etc/systemd/system/proxy.service
  template:
    src: proxy.service.j2
    dest: "{{etc}}/systemd/system/proxy.service"
    owner: root
    group: root
    mode: '664'

- name: Reoload systemctl service file 
  systemd:
    daemon_reload: true
    name: proxy
    state: started
    enabled: true

- name: Verify that the proxy is working
  uri:
    url: "http://proxy.{{hostname}}.{{domain_name}}"

