- name: Install all the package for wordpress setup
  dnf:
    name:
      - php-mysqlnd
      - php-fpm 
      - mariadb-server
      - httpd
      - tar
      - curl
      - php-json

- name: Start mariadb
  systemd:
    name: mariadb
    state: started
    enabled: true

# In case the mysqlclient is not install on the machine we can do it now 
#
- name: Install PyMySQL with pip to use mysql_user and mysql_db later 
  pip:
    name: PyMySQL
    state: latest


# Now we are going to do the database configuration with mysql_user

- name: Set a root password 
  mysql_user:
    login_user: root
    login_password: "{{sql_root_password}}"
    user: root
    password: "{{sql_root_password}}"

- name: Remove all anymous user accounts
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: root
    login_password: "{{sql_root_password}}"

- name: Remove the MySQL test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{sql_root_password}}"

- name: Create a database named wordpress
  mysql_db:
    name: wordpress
    state: present
    login_user: root
    login_password: "{{sql_root_password}}"

- name: Create a user named admin
  mysql_user:
    name: admin
    password: pass
    state: present
    priv: 'WordPress.*:ALL,GRANT'
    login_user: root
    login_password: "{{sql_root_password}}"
- name: Let's download wrodrpess with the curl command
  command: curl https://wordpress.org/latest.tar.gz --output wordpress.tar.gz
- name: Unarchive the directory download
  unarchive:
    src: "{{home}}/wordpress.tar.gz"
    dest: "{{home}}/"
    owner: centos 
    group: centos

- name: Copy the file to the path /var/www/html 
  # I had some problem to use copy and synchronize because of the root user
  command: sudo cp -r wordpress {{var}}/www/html/wordpress

- name: Change the owner and the group to the directory
  file:
    path: "{{var}}/www/html/wordpress.{{hostname}}"
    owner: apache
    group: apache 
    state: directory
    recurse: true

- name: Sefcontext | this equates to 'chcon -t httpd_sys_rw_content_t /var/www/html/wordpress.c31348 -R'
  sefcontext:
   target: '{{var}}/www/html/wordpress.{{hostname}}(/.*)?'
   setype: httpd_sys_rw_content_t
   state: present

- name: Change the error_log=/var/log/httpd/php-errors.log in the /etc/php-fpm.conf
  template:
    src: php-fpm.conf.j2
    dest: "{{etc}}/php-fpm.conf"

# I don't know why this is not working but maybe I should do this by hand
- name: Change the error_log=/var/log/httpd/www-php-errors.log in the /etc/php-fpm.d/www.conf
  copy:
    src: www.conf
    dest: "{{etc}}/php-fpm.d/www.conf"

- name: Create the error log file in /var/log/httpd/php-errors.log
  copy:
    content: ""
    dest: "{{var}}/log/httpd/php-errors.log"
    owner: apache 
    group: apache


- name: Create the error log file in /var/log/hpttd/www-php-errors.log
  copy:
    content: ""
    dest: "{{var}}/log/httpd/www-php-errors.log"
    owner: apache
    group: apache

- name: Create the virtual host pointing at wordpress in /etc/httpd/conf.d/wordpress.conf
  template:
    src: wordpress.conf.j2
    dest: "{{etc}}/httpd/conf.d/wordpress.conf"

- name: Create the file for forensic log in /var/log/httpd/wordpress-forensic.log
  copy:
    content: ""
    dest: "{{var}}/log/httpd/wordpress-forensic.log"

- name: Reload httpd
  service:
    name: httpd
    state: reloaded

- name: Start the php-fpm service
  service:
    name: php-fpm
    state: started
