- name: open the port 53  with firewalld
  firewalld:
    port: 53/tcp
    permanent: true
    state: enabled
    immediate: true
  notify: 'reload firewall'


- name: open the port 53  with firewalld
  firewalld:
    port: 53/udp
    permanent: true
    state: enabled
    immediate: true
  notify: 'reload firewall'

- name: open the port 8301 with firewalld
  firewalld:
    port: 8301/tcp
    permanent: true
    state: enabled
    immediate: true
  notify: 'reload firewall'   


- name: open the port 8301 with firewalld
  firewalld:
    port: 8301/udp
    permanent: true
    state: enabled
    immediate: true
  notify: 'reload firewall'    

- name: DNS | Autoremove unneeded packages installed as dependencie
  dnf:
    autoremove: yes
- name: Disable IPv6
  copy:
    src: 70-ipv6.conf
    dest: /etc/sysctl.d/70-ipv6.conf
    owner: root 
    group: root 
    mode: '0644'

- name: Change net.ipv6.conf.default.disable_ipv6 to 1.
  sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: '1'
    sysctl_file: /etc/sysctl.d/70-ipv6.conf
    reload: yes

- name: Change net.ipv6.conf.all.disable_ipv6 to 1.
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: '1'
    sysctl_file: /etc/sysctl.d/70-ipv6.conf
    reload: yes

      #Hostname modification to corresponds to our own hostname

- name: Inserts into hostname
  template: 
    src: hostname.j2
    dest: /etc/hostname
    owner: root
    group: root
    mode: '644'

- name: Inserts into hosts 
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '644'

      ## File and directory creation in /var/named
      # To use this file properly don't forget to add 
      # the / before all the file because wihtout this 
      # it will not create the files in the right place
    
- name: Creates log in /var/named
  file:
    path: "{{ var }}/named/log"
    state: directory
    owner: root
    group: named
    mode: '770'

      # This action allows to create multiple files 
      # in a certain location

- name: Creates all the files in /var/named/log
  copy:
    content: ""
    dest: "{{var}}/named/log/{{item}}"
    force: no
    mode: '770'
    owner: root
    group: named  
  with_items:
    - default
    - auth_servers
    - zone_transfers
    - client_security
    - queries
    - query-errors
 

      #Start the named service
      # but this is useless in our case because if named is stop
      # the first action of the playbook cannot be played.


- name: Put the personnalize configuration file named in /etc/named.conf
  template:
    src: named.conf.j2
    dest: "{{etc}}/named.conf"
    backup: true


- name: Start named service
  service:
    name: named
    state: started

      # As its name indicates this enable to auto-starting the named  
- name: Enable auto-starting the named
  service:
    name: named
    enabled: yes

      ## Here again if the use is real don't forget to add 
      # the '/' before the etc/named.conf

- name: Put the personnalize configuration file named in /etc/named.conf
  template:
    src: named.conf.j2
    dest: "{{etc}}/named.conf"
    backup: true
  
      ## Same thing here as before 
  
- name: Put the personnalize configuration file of the resolver in /etc/resolv.conf
  template:
    src: resolv.conf.j2
    dest: "{{etc}}/resolv.conf"
    backup: true

      #Same thing as before with the '/' before etc
      # Create a directoy named if it doesn't exist

- name: Creates the directory /etc/named
  file:
    path: "{{etc}}/named"      
    state: directory
    owner: root
    group: named
    mode: '750'

        # Creation of the two zone file normal and reverse one
        # Here again for the 

- name: Create the zone file of my domain name in /etc/named
  template:
    src: dns.zone.j2
    dest: "{{etc}}/named/{{hostname}}.{{domain_name}}"
    owner: root
    group: root
    mode: '644'

- name: Create the zone file for the reverse mapping in /etc/named
  template:
    src: dns.reverse.zone.j2
    dest: "{{etc}}/named/reverse.{{hostname}}.{{domain_name}}"
    owner: root
    group: root
    mode: '644'

